## Caching the inverse of a matrix

## makeCacheMatrix(): Creates a special matrix that caches the inverse of a matrix
# if already run, to reduce computation time

makeCacheMatrix <- function(x = matrix()) {
        i <- NULL
        set <- function (z){
                x <<- z
                i <<- NULL
        }
        get <- function() x
        setinv <- function(solve) i <<- solve
        getinv <- function() i
        list(set = set, get = get, setinv = setinv, getinv = getinv)
        
}


## The function solves for the inverse of a matrix but uses list generated by makeCacheMatrix
# to check if an inverse has already been computed.

cacheSolve <- function(x, ...) {
        i <- x$getinv()
        if(!is.null(i)){
                message("using cached data")
                return(i)
        }
        
        data <- x$get()
        i <- solve(data,...)
        x$setinv(i)
        i
}


